//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4338
{
    using System;
    using System.Collections.Generic;
    
    public partial class isrpo
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string KOD { get; set; }
        public string DAtta { get; set; }
        public string INNdex { get; set; }
        public string GOROD { get; set; }
        public string ULICA { get; set; }
        public string DOM { get; set; }
        public string KV { get; set; }
        public string email { get; set; }
        public int vozrast { get; set; }
        public isrpo(string fIO, string kOD, string dAtta, string iNNdex, string gOROD, string uLICA, string dOM, string kV, string email)
        {
            FIO = fIO;
            KOD = kOD;
            DAtta = dAtta;
            INNdex = iNNdex;
            GOROD = gOROD;
            ULICA = uLICA;
            DOM = dOM;
            KV = kV;
            this.email = email;
        }
        public isrpo() { }
    }
}
